version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - "9000:80"
    depends_on:
      - ${DB_CONTAINER}
    entrypoint: ["sh", "/var/www/docker-entrypoint.sh"]

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
